### ISSUE TITLE
Fix reply crosspost to twitter with media

### ISSUE THREAD

**Issue by JohnnyEn** [JohnnyEn/mkconnector#7]
```ApiResponseError: Request failed with code 403 - Missing required parameter: status. (Twitter code 170)
    at RequestHandlerHelper.createResponseError (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:252:25)
    at Gunzip.emit (node:events:513:28)
    at Gunzip.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    date: 'Mon, 31 Oct 2022 18:04:42 GMT',
    perf: '7626143928',
    pragma: 'no-cache',
    server: 'tsa_o',
    status: '403 Forbidden',
    expires: 'Tue, 31 Mar 1981 05:00:00 GMT',
    'set-cookie': [
      'lang=en; Path=/',
      'guest_id=________; Max-Age=34214400; Expires=Fri, 01 Dec 2023 18:04:42 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    ],
    'content-type': 'application/json;charset=utf-8',
    'cache-control': 'no-cache, no-store, must-revalidate, pre-check=0, post-check=0',
    'last-modified': 'Mon, 31 Oct 2022 18:04:42 GMT',
    'x-transaction': '__________',
    'content-length': '98',
    'x-access-level': 'read-write',
    'x-frame-options': 'SAMEORIGIN',
    'content-encoding': 'gzip',
    'x-transaction-id': '_________',
    'x-xss-protection': '0',
    'content-disposition': 'attachment; filename=json.json',
    'x-content-type-options': 'nosniff',
    'x-twitter-response-tags': 'BouncerCompliant',
    'strict-transport-security': 'max-age=631138519',
    'x-response-time': '167',
    'x-connection-hash': '___________',
    connection: 'close'
  },
  rateLimit: undefined,
  data: {
    errors: [ { code: 170, message: 'Missing required parameter: status.' } ]
  },
  errors: [ { code: 170, message: 'Missing required parameter: status.' } ]
}
```

**Comment by JohnnyEn** [comment]
fixed with https://github.com/JohnnyEn/mkconnector/pull/9
